
package com.zsq.base.entity;

// Generated 2015-9-16 15:53:41 by Hibernate Tools 3.4.0.CR1

/**
 * Opermode generated by hbm2java
 */
public class Opermode
{
    private Integer id;
    private String value;
    private String name;

    public Opermode()
    {
    }

    public Opermode(String value, String name)
    {
        this.value = value;
        this.name = name;
    }

    public Integer getId()
    {
        return this.id;
    }

    public void setId(Integer id)
    {
        this.id = id;
    }

    public String getValue()
    {
        return this.value;
    }

    public void setValue(String value)
    {
        this.value = value;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

}
