
package com.zsq.base.entity;

// Generated 2015-9-16 15:53:41 by Hibernate Tools 3.4.0.CR1

/**
 * Operstepmode generated by hbm2java
 */
public class Operstepmode
{
    private Integer id;
    private Short address;
    private String value;
    private String name;

    public Operstepmode()
    {
    }

    public Operstepmode(Short address, String value, String name)
    {
        this.address = address;
        this.value = value;
        this.name = name;
    }

    public Integer getId()
    {
        return this.id;
    }

    public void setId(Integer id)
    {
        this.id = id;
    }

    public Short getAddress()
    {
        return this.address;
    }

    public void setAddress(Short address)
    {
        this.address = address;
    }

    public String getValue()
    {
        return this.value;
    }

    public void setValue(String value)
    {
        this.value = value;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

}
