
package com.zsq.base.entity;

// Generated 2015-9-16 15:53:41 by Hibernate Tools 3.4.0.CR1

/**
 * Pctype generated by hbm2java
 */
public class Pctype
{
    private Integer id;
    private String name;

    public Pctype()
    {
    }

    public Pctype(String name)
    {
        this.name = name;
    }

    public Integer getId()
    {
        return this.id;
    }

    public void setId(Integer id)
    {
        this.id = id;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

}
